language: node_js
before_install:
  - npm i -g npm@8.9.4
cache:
  directories:
    - "node_modules"
script: 
  - npm run clean:chrome
  - npm run clean:firefox
  - npm run build:chrome
  - npm run build:firefox
  - npm run pack:chrome
  - npm run pack:firefox